version: 2
ethernets:
  ens18:                       # 2 espaces
    dhcp4: false               # 4 espaces
    addresses:
      - ${ip_cidr}             # 6 espaces
    gateway4: ${gateway}
    nameservers:
      addresses:               # 6 espaces
        - ${dns1}              # 8 espaces
        - ${dns2}