all:
  vars:
    ansible_user: ladmin
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ip_zabbix_server: "192.168.10.51" 

  hosts:
    bastion:
      ansible_host: 192.168.10.50
    web:
      ansible_host: 192.168.10.51
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ProxyJump=ladmin@192.168.10.50"
    db:
      ansible_host: 192.168.10.52
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ProxyJump=ladmin@192.168.10.50"

  children:
    web_servers:
      hosts:
        web:
    bastions:
      hosts:
        bastion:
    databases:
      hosts:
        db: