all:
  vars:
    ansible_user: ladmin
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  hosts:
    bastion:
      ansible_host: 192.168.10.50
    web:
      ansible_host: 192.168.10.51
    db:
      ansible_host: 192.168.10.52